#!/usr/bin/env bash
set -e

USER=allenda8
HOST=66.147.244.54
APP=SonicParts
SCRIPT_NAME=parts_server

echo "Deploying $APP from Git master branch..."
echo
ssh $USER@$HOST "cd public_html/$APP && git checkout -f && git pull && bundle install && bundle exec rake db:migrate && bundle exec ruby ${SCRIPT_NAME}_control.rb restart"
echo
echo "Deployed $APP."
